### ISSUE TITLE
Check if (LDAP) user exists before authenticate

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-authentication#2]
I'm looking for a way to check if my user really exists before I authenticate it.

Is this library capable of doing so or do I need to use \Zend\Ldap for this ?

It would be a pity if you need to use \Zend\Ldap as the serveroptions differ.

---

Originally posted by @Yamakasi at https://github.com/zendframework/zend-authentication/issues/35

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
