### ISSUE TITLE
remove @deprecated class and method

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-authentication#9]
---

Originally posted by @samsonasik at https://github.com/zendframework/zend-authentication/pull/2

**Comment by weierophinney** [comment]
bump php version in composer :-)


---

Originally posted by @vaclavvanik at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-108829073

**Comment by weierophinney** [comment]
@vaclavvanik This PR does not imply a change in PHP requirements.


---

Originally posted by @Maks3w at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-108830012

**Comment by weierophinney** [comment]
Oh, you are right. I thought rashly


---

Originally posted by @vaclavvanik at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-108832313

**Comment by weierophinney** [comment]
rebased


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-109490058

**Comment by weierophinney** [comment]
I'll close this until v3 development of this component begin


---

Originally posted by @Maks3w at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-109812195

**Comment by weierophinney** [comment]
:(. this is why I think we need to have per-branch : 2.4, 2.5, 2.6, 3.0 , early works merged is better imo.
//cc @gianarb @weierophinney 


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-109826769

**Comment by weierophinney** [comment]
This can begin _now_ on the _develop_ branch. Essentially, this PR is indicating that we have developers wanting to work on BC-breaking changes, which means that the develop branch should become the 3.0 branch. I'll review, and, on merge, bump the branch aliases for the develop branch.


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-110043990

**Comment by weierophinney** [comment]
mergeable? Or i should re-create PR against develop branch?


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-229833623

**Comment by weierophinney** [comment]
@weierophinney I've changed target branch to develop


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-245891215

**Comment by weierophinney** [comment]
@weierophinney merge-able ?


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-254091657

**Comment by weierophinney** [comment]
Is there anything I can do to get it merged? Thank you.

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-authentication/pull/2#issuecomment-313709218

**Comment by samsonasik** [comment]
I've created PR https://github.com/laminas/laminas-authentication/pull/11 for it.

**Comment by froschdesign** [comment]
Fixed with #11 and will be released with [version 3.0.0](https://github.com/laminas/laminas-authentication/milestone/2?closed=1).
